#' Data set containing NUTS-Classifications
#'
#' @description A function that returns a reference table for NUTS regions including IDs and names.
#' @param cache_dir Object of class \code{character}. Indicates a path where the return object is cached.
#'
#' @return An object of class \code{data.frame} containing NUTS-Codes and names of the regions considered in the SUSPend project.
#' @export
#'
#' @importFrom magrittr %>%
#' @importFrom dplyr select mutate

nuts_table <- function(cache_dir = tempdir()){
  NUTS_3 <- c("AT111", "AT112", "AT113", "AT121", "AT122", "AT123", "AT124", "AT125", "AT126", "AT127",
              "AT130", "AT211", "AT212", "AT213", "AT221", "AT222", "AT223", "AT224", "AT225", "AT226",
              "AT311", "AT312", "AT313", "AT314", "AT315", "AT321", "AT322", "AT323", "AT331", "AT332",
              "AT333", "AT334", "AT335", "AT341", "AT342", "CH011", "CH012", "CH013", "CH021", "CH022",
              "CH023", "CH024", "CH025", "CH031", "CH032", "CH033", "CH040", "CH051", "CH052", "CH053",
              "CH054", "CH055", "CH056", "CH057", "CH061", "CH062", "CH063", "CH064", "CH065", "CH066",
              "CH070", "DE111", "DE112", "DE113", "DE114", "DE115", "DE116", "DE117", "DE118", "DE119",
              "DE11A", "DE11B", "DE11C", "DE11D", "DE121", "DE122", "DE123", "DE124", "DE125", "DE126",
              "DE127", "DE128", "DE129", "DE12A", "DE12B", "DE12C", "DE131", "DE132", "DE133", "DE134",
              "DE135", "DE136", "DE137", "DE138", "DE139", "DE13A", "DE141", "DE142", "DE143", "DE144",
              "DE145", "DE146", "DE147", "DE148", "DE149", "DE211", "DE212", "DE213", "DE214", "DE215",
              "DE216", "DE217", "DE218", "DE219", "DE21A", "DE21B", "DE21C", "DE21D", "DE21E", "DE21F",
              "DE21G", "DE21H", "DE21I", "DE21J", "DE21K", "DE21L", "DE21M", "DE21N", "DE221", "DE222",
              "DE223", "DE224", "DE225", "DE226", "DE227", "DE228", "DE229", "DE22A", "DE22B", "DE22C",
              "DE231", "DE232", "DE233", "DE234", "DE235", "DE236", "DE237", "DE238", "DE239", "DE23A",
              "DE241", "DE242", "DE243", "DE244", "DE245", "DE246", "DE247", "DE248", "DE249", "DE24A",
              "DE24B", "DE24C", "DE24D", "DE251", "DE252", "DE253", "DE254", "DE255", "DE256", "DE257",
              "DE258", "DE259", "DE25A", "DE25B", "DE25C", "DE261", "DE262", "DE263", "DE264", "DE265",
              "DE266", "DE267", "DE268", "DE269", "DE26A", "DE26B", "DE26C", "DE271", "DE272", "DE273",
              "DE274", "DE275", "DE276", "DE277", "DE278", "DE279", "DE27A", "DE27B", "DE27C", "DE27D",
              "DE27E", "DE300", "DE401", "DE402", "DE403", "DE404", "DE405", "DE406", "DE407", "DE408",
              "DE409", "DE40A", "DE40B", "DE40C", "DE40D", "DE40E", "DE40F", "DE40G", "DE40H", "DE40I",
              "DE501", "DE502", "DE600", "DE711", "DE712", "DE713", "DE714", "DE715", "DE716", "DE717",
              "DE718", "DE719", "DE71A", "DE71B", "DE71C", "DE71D", "DE71E", "DE721", "DE722", "DE723",
              "DE724", "DE725", "DE731", "DE732", "DE733", "DE734", "DE735", "DE736", "DE737", "DE803",
              "DE804", "DE80J", "DE80K", "DE80L", "DE80M", "DE80N", "DE80O", "DE911", "DE912", "DE913",
              "DE914", "DE916", "DE917", "DE918", "DE91A", "DE91B", "DE91C", "DE922", "DE923", "DE925",
              "DE926", "DE927", "DE928", "DE929", "DE931", "DE932", "DE933", "DE934", "DE935", "DE936",
              "DE937", "DE938", "DE939", "DE93A", "DE93B", "DE941", "DE942", "DE943", "DE944", "DE945",
              "DE946", "DE947", "DE948", "DE949", "DE94A", "DE94B", "DE94C", "DE94D", "DE94E", "DE94F",
              "DE94G", "DE94H", "DEA11", "DEA12", "DEA13", "DEA14", "DEA15", "DEA16", "DEA17", "DEA18",
              "DEA19", "DEA1A", "DEA1B", "DEA1C", "DEA1D", "DEA1E", "DEA1F", "DEA22", "DEA23", "DEA24",
              "DEA26", "DEA27", "DEA28", "DEA29", "DEA2A", "DEA2B", "DEA2C", "DEA2D", "DEA31", "DEA32",
              "DEA33", "DEA34", "DEA35", "DEA36", "DEA37", "DEA38", "DEA41", "DEA42", "DEA43", "DEA44",
              "DEA45", "DEA46", "DEA47", "DEA51", "DEA52", "DEA53", "DEA54", "DEA55", "DEA56", "DEA57",
              "DEA58", "DEA59", "DEA5A", "DEA5B", "DEA5C", "DEB11", "DEB12", "DEB13", "DEB14", "DEB15",
              "DEB17", "DEB18", "DEB1A", "DEB1B", "DEB1C", "DEB1D", "DEB21", "DEB22", "DEB23", "DEB24",
              "DEB25", "DEB31", "DEB32", "DEB33", "DEB34", "DEB35", "DEB36", "DEB37", "DEB38", "DEB39",
              "DEB3A", "DEB3B", "DEB3C", "DEB3D", "DEB3E", "DEB3F", "DEB3G", "DEB3H", "DEB3I", "DEB3J",
              "DEB3K", "DEC01", "DEC02", "DEC03", "DEC04", "DEC05", "DEC06", "DED21", "DED2C", "DED2D",
              "DED2E", "DED2F", "DED41", "DED42", "DED43", "DED44", "DED45", "DED51", "DED52", "DED53",
              "DEE01", "DEE02", "DEE03", "DEE04", "DEE05", "DEE06", "DEE07", "DEE08", "DEE09", "DEE0A",
              "DEE0B", "DEE0C", "DEE0D", "DEE0E", "DEF01", "DEF02", "DEF03", "DEF04", "DEF05", "DEF06",
              "DEF07", "DEF08", "DEF09", "DEF0A", "DEF0B", "DEF0C", "DEF0D", "DEF0E", "DEF0F", "DEG01",
              "DEG02", "DEG03", "DEG04", "DEG05", "DEG06", "DEG07", "DEG09", "DEG0A", "DEG0B", "DEG0C",
              "DEG0D", "DEG0E", "DEG0F", "DEG0G", "DEG0H", "DEG0I", "DEG0J", "DEG0K", "DEG0L", "DEG0M",
              "DEG0N", "DEG0P", "FR101", "FR102", "FR103", "FR104", "FR105", "FR106", "FR107", "FR108",
              "FRB01", "FRB02", "FRB03", "FRB04", "FRB05", "FRB06", "FRC11", "FRC12", "FRC13", "FRC14",
              "FRC21", "FRC22", "FRC23", "FRC24", "FRD11", "FRD12", "FRD13", "FRD21", "FRD22", "FRE11",
              "FRE12", "FRE21", "FRE22", "FRE23", "FRF11", "FRF12", "FRF21", "FRF22", "FRF23", "FRF24",
              "FRF31", "FRF32", "FRF33", "FRF34", "FRG01", "FRG02", "FRG03", "FRG04", "FRG05", "FRH01",
              "FRH02", "FRH03", "FRH04", "FRI11", "FRI12", "FRI13", "FRI14", "FRI15", "FRI21", "FRI22",
              "FRI23", "FRI31", "FRI32", "FRI33", "FRI34", "FRJ11", "FRJ12", "FRJ13", "FRJ14", "FRJ15",
              "FRJ21", "FRJ22", "FRJ23", "FRJ24", "FRJ25", "FRJ26", "FRJ27", "FRJ28", "FRK11", "FRK12",
              "FRK13", "FRK14", "FRK21", "FRK22", "FRK23", "FRK24", "FRK25", "FRK26", "FRK27", "FRK28",
              "FRL01", "FRL02", "FRL03", "FRL04", "FRL05", "FRL06", "FRM01", "FRM02", "ITC11", "ITC12",
              "ITC13", "ITC14", "ITC15", "ITC16", "ITC17", "ITC18", "ITC20", "ITC31", "ITC32", "ITC33",
              "ITC34", "ITC41", "ITC42", "ITC43", "ITC44", "ITC46", "ITC47", "ITC48", "ITC49", "ITC4A",
              "ITC4B", "ITC4C", "ITC4D", "ITF11", "ITF12", "ITF13", "ITF14", "ITF21", "ITF22", "ITF31",
              "ITF32", "ITF33", "ITF34", "ITF35", "ITF43", "ITF44", "ITF45", "ITF46", "ITF47", "ITF48",
              "ITF51", "ITF52", "ITF61", "ITF62", "ITF63", "ITF64", "ITF65", "ITG11", "ITG12", "ITG13",
              "ITG14", "ITG15", "ITG16", "ITG17", "ITG18", "ITG19", "ITG2D", "ITG2E", "ITG2F", "ITG2G",
              "ITG2H", "ITH10", "ITH20", "ITH31", "ITH32", "ITH33", "ITH34", "ITH35", "ITH36", "ITH37",
              "ITH41", "ITH42", "ITH43", "ITH44", "ITH51", "ITH52", "ITH53", "ITH54", "ITH55", "ITH56",
              "ITH57", "ITH58", "ITH59", "ITI11", "ITI12", "ITI13", "ITI14", "ITI15", "ITI16", "ITI17",
              "ITI18", "ITI19", "ITI1A", "ITI21", "ITI22", "ITI31", "ITI32", "ITI33", "ITI34", "ITI35",
              "ITI41", "ITI42", "ITI43", "ITI44", "ITI45", "LI000")

  NUTS_3_NAMES <- c("Mittelburgenland", "Nordburgenland", "S\u00FCdburgenland", "Mostviertel-Eisenwurzen",
                    "Nieder\u00F6sterreich-S\u00FCd", "Sankt P\u00F6lten", "Waldviertel", "Weinviertel",
                    "Wiener Umland/Nordteil", "Wiener Umland/S\u00FCdteil", "Wien", "Klagenfurt-Villach",
                    "Oberk\u00E4rnten", "Unterk\u00E4rnten", "Graz", "Liezen", "\u00D6stliche Obersteiermark",
                    "Oststeiermark", "West- und S\u00FCdsteiermark", "Westliche Obersteiermark", "Innviertel",
                    "Linz-Wels", "M\u00FChlviertel", "Steyr-Kirchdorf", "Traunviertel", "Lungau",
                    "Pinzgau-Pongau", "Salzburg und Umgebung", "Au\u00DFerfern", "Innsbruck", "Osttirol",
                    "Tiroler Oberland", "Tiroler Unterland", "Bludenz-Bregenzer Wald",
                    "Rheintal-Bodenseegebiet", "Vaud", "Valais", "Gen\u00E8ve", "Bern", "Freiburg",
                    "Solothurn", "Neuch\u00E2tel", "Jura", "Basel-Stadt", "Basel-Landschaft", "Aargau",
                    "Z\u00FCrich", "Glarus", "Schaffhausen", "Appenzell Ausserrhoden", "Appenzell Innerrhoden",
                    "St. Gallen", "Graub\u00FCnden", "Thurgau", "Luzern", "Uri", "Schwyz", "Obwalden",
                    "Nidwalden", "Zug", "Ticino", "Stuttgart, Stadtkreis", "B\u00F6blingen", "Esslingen",
                    "G\u00F6ppingen", "Ludwigsburg", "Rems-Murr-Kreis", "Heilbronn, Stadtkreis",
                    "Heilbronn, Landkreis", "Hohenlohekreis", "Schw\u00E4bisch Hall", "Main-Tauber-Kreis",
                    "Heidenheim", "Ostalbkreis", "Baden-Baden, Stadtkreis", "Karlsruhe, Stadtkreis",
                    "Karlsruhe, Landkreis", "Rastatt", "Heidelberg, Stadtkreis", "Mannheim, Stadtkreis",
                    "Neckar-Odenwald-Kreis", "Rhein-Neckar-Kreis", "Pforzheim, Stadtkreis", "Calw",
                    "Enzkreis", "Freudenstadt", "Freiburg im Breisgau, Stadtkreis",
                    "Breisgau-Hochschwarzwald", "Emmendingen", "Ortenaukreis", "Rottweil",
                    "Schwarzwald-Baar-Kreis", "Tuttlingen", "Konstanz", "L\u00F6rrach", "Waldshut",
                    "Reutlingen", "T\u00FCbingen, Landkreis", "Zollernalbkreis", "Ulm, Stadtkreis",
                    "Alb-Donau-Kreis", "Biberach", "Bodenseekreis", "Ravensburg", "Sigmaringen",
                    "Ingolstadt, Kreisfreie Stadt", "M\u00FCnchen, Kreisfreie Stadt",
                    "Rosenheim, Kreisfreie Stadt", "Alt\u00F6tting", "Berchtesgadener Land",
                    "Bad T\u00F6lz-Wolfratshausen", "Dachau", "Ebersberg", "Eichst\u00E4tt", "Erding",
                    "Freising", "F\u00FCrstenfeldbruck", "Garmisch-Partenkirchen", "Landsberg am Lech",
                    "Miesbach", "M\u00FChldorf a. Inn", "M\u00FCnchen, Landkreis", "Neuburg-Schrobenhausen",
                    "Pfaffenhofen a. d. Ilm", "Rosenheim, Landkreis", "Starnberg", "Traunstein",
                    "Weilheim-Schongau", "Landshut, Kreisfreie Stadt", "Passau, Kreisfreie Stadt",
                    "Straubing, Kreisfreie Stadt", "Deggendorf", "Freyung-Grafenau", "Kelheim",
                    "Landshut, Landkreis", "Passau, Landkreis", "Regen", "Rottal-Inn", "Straubing-Bogen",
                    "Dingolfing-Landau", "Amberg, Kreisfreie Stadt", "Regensburg, Kreisfreie Stadt",
                    "Weiden i. d. Opf, Kreisfreie Stadt", "Amberg-Sulzbach", "Cham", "Neumarkt i. d. OPf.",
                    "Neustadt a. d. Waldnaab", "Regensburg, Landkreis", "Schwandorf", "Tirschenreuth",
                    "Bamberg, Kreisfreie Stadt", "Bayreuth, Kreisfreie Stadt", "Coburg, Kreisfreie Stadt",
                    "Hof, Kreisfreie Stadt", "Bamberg, Landkreis", "Bayreuth, Landkreis",
                    "Coburg, Landkreis", "Forchheim", "Hof, Landkreis", "Kronach", "Kulmbach",
                    "Lichtenfels", "Wunsiedel i. Fichtelgebirge", "Ansbach, Kreisfreie Stadt",
                    "Erlangen, Kreisfreie Stadt", "F\u00FCrth, Kreisfreie Stadt", "N\u00FCrnberg, Kreisfreie Stadt",
                    "Schwabach, Kreisfreie Stadt", "Ansbach, Landkreis", "Erlangen-H\u00F6chstadt",
                    "F\u00FCrth, Landkreis", "N\u00FCrnberger Land", "Neustadt a. d. Aisch-Bad Windsheim",
                    "Roth", "Wei\u00DFenburg-Gunzenhausen", "Aschaffenburg, Kreisfreie Stadt",
                    "Schweinfurt, Kreisfreie Stadt", "W\u00FCrzburg, Kreisfreie Stadt",
                    "Aschaffenburg, Landkreis", "Bad Kissingen", "Rh\u00F6n-Grabfeld", "Ha\u00DFberge", "Kitzingen",
                    "Miltenberg", "Main-Spessart", "Schweinfurt, Landkreis", "W\u00FCrzburg, Landkreis",
                    "Augsburg, Kreisfreie Stadt", "Kaufbeuren, Kreisfreie Stadt",
                    "Kempten (Allg\u00E4u), Kreisfreie Stadt", "Memmingen, Kreisfreie Stadt", "Aichach-Friedberg",
                    "Augsburg, Landkreis", "Dillingen a.d. Donau", "G\u00FCnzburg", "Neu-Ulm", "Lindau (Bodensee)",
                    "Ostallg\u00E4u", "Unterallg\u00E4u", "Donau-Ries", "Oberallg\u00E4u", "Berlin",
                    "Brandenburg an der Havel, Kreisfreie Stadt", "Cottbus, Kreisfreie Stadt",
                    "Frankfurt (Oder), Kreisfreie Stadt", "Potsdam, Kreisfreie Stadt", "Barnim",
                    "Dahme-Spreewald", "Elbe-Elster", "Havelland", "M\u00E4rkisch-Oderland", "Oberhavel",
                    "Oberspreewald-Lausitz", "Oder-Spree", "Ostprignitz-Ruppin", "Potsdam-Mittelmark",
                    "Prignitz", "Spree-Nei\u00DFe", "Teltow-Fl\u00E4ming", "Uckermark", "Bremen, Kreisfreie Stadt",
                    "Bremerhaven, Kreisfreie Stadt", "Hamburg", "Darmstadt, Kreisfreie Stadt",
                    "Frankfurt am Main, Kreisfreie Stadt", "Offenbach am Main, Kreisfreie Stadt",
                    "Wiesbaden, Kreisfreie Stadt", "Bergstra\u00DFe", "Darmstadt-Dieburg", "Gro\u00DF-Gerau",
                    "Hochtaunuskreis", "Main-Kinzig-Kreis", "Main-Taunus-Kreis", "Odenwaldkreis",
                    "Offenbach, Landkreis", "Rheingau-Taunus-Kreis", "Wetteraukreis", "Gie\u00DFen, Landkreis",
                    "Lahn-Dill-Kreis", "Limburg-Weilburg", "Marburg-Biedenkopf", "Vogelsbergkreis",
                    "Kassel, Kreisfreie Stadt", "Fulda", "Hersfeld-Rotenburg", "Kassel, Landkreis",
                    "Schwalm-Eder-Kreis", "Waldeck-Frankenberg", "Werra-Mei\u00DFner-Kreis",
                    "Rostock, Kreisfreie Stadt", "Schwerin, Kreisfreie Stadt", "Mecklenburgische Seenplatte",
                    "Landkreis Rostock", "Vorpommern-R\u00FCgen", "Nordwestmecklenburg", "Vorpommern-Greifswald",
                    "Ludwigslust-Parchim", "Braunschweig, Kreisfreie Stadt", "Salzgitter, Kreisfreie Stadt",
                    "Wolfsburg, Kreisfreie Stadt", "Gifhorn", "Goslar", "Helmstedt", "Northeim", "Peine",
                    "Wolfenb\u00FCttel", "G\u00F6ttingen", "Diepholz", "Hameln-Pyrmont", "Hildesheim", "Holzminden",
                    "Nienburg (Weser)", "Schaumburg", "Region Hannover", "Celle", "Cuxhaven", "Harburg",
                    "L\u00FCchow-Dannenberg", "L\u00FCneburg, Landkreis", "Osterholz", "Rotenburg (W\u00FCmme)",
                    "Heidekreis", "Stade", "Uelzen", "Verden", "Delmenhorst, Kreisfreie Stadt",
                    "Emden, Kreisfreie Stadt", "Oldenburg (Oldenburg), Kreisfreie Stadt",
                    "Osnabr\u00FCck, Kreisfreie Stadt", "Wilhelmshaven, Kreisfreie Stadt", "Ammerland",
                    "Aurich", "Cloppenburg", "Emsland", "Friesland (DE)", "Grafschaft Bentheim", "Leer",
                    "Oldenburg, Landkreis", "Osnabr\u00FCck, Landkreis", "Vechta", "Wesermarsch", "Wittmund",
                    "D\u00FCsseldorf, Kreisfreie Stadt", "Duisburg, Kreisfreie Stadt", "Essen, Kreisfreie Stadt",
                    "Krefeld, Kreisfreie Stadt", "M\u00F6nchengladbach, Kreisfreie Stadt",
                    "M\u00FClheim an der Ruhr, Kreisfreie Stadt", "Oberhausen, Kreisfreie Stadt",
                    "Remscheid, Kreisfreie Stadt", "Solingen, Kreisfreie Stadt",
                    "Wuppertal, Kreisfreie Stadt", "Kleve", "Mettmann", "Rhein-Kreis Neuss", "Viersen",
                    "Wesel", "Bonn, Kreisfreie Stadt", "K\u00F6ln, Kreisfreie Stadt",
                    "Leverkusen, Kreisfreie Stadt", "D\u00FCren", "Rhein-Erft-Kreis", "Euskirchen", "Heinsberg",
                    "Oberbergischer Kreis", "Rheinisch-Bergischer Kreis", "Rhein-Sieg-Kreis",
                    "St\u00E4dteregion Aachen", "Bottrop, Kreisfreie Stadt", "Gelsenkirchen, Kreisfreie Stadt",
                    "M\u00FCnster, Kreisfreie Stadt", "Borken", "Coesfeld", "Recklinghausen", "Steinfurt",
                    "Warendorf", "Bielefeld, Kreisfreie Stadt", "G\u00FCtersloh", "Herford", "H\u00F6xter", "Lippe",
                    "Minden-L\u00FCbbecke", "Paderborn", "Bochum, Kreisfreie Stadt", "Dortmund, Kreisfreie Stadt",
                    "Hagen, Kreisfreie Stadt", "Hamm, Kreisfreie Stadt", "Herne, Kreisfreie Stadt",
                    "Ennepe-Ruhr-Kreis", "Hochsauerlandkreis", "M\u00E4rkischer Kreis", "Olpe", "Siegen-Wittgenstein",
                    "Soest", "Unna", "Koblenz, Kreisfreie Stadt", "Ahrweiler", "Altenkirchen (Westerwald)",
                    "Bad Kreuznach", "Birkenfeld", "Mayen-Koblenz", "Neuwied", "Rhein-Lahn-Kreis", "Westerwaldkreis",
                    "Cochem-Zell", "Rhein-Hunsr\u00FCck-Kreis", "Trier, Kreisfreie Stadt", "Bernkastel-Wittlich",
                    "Eifelkreis Bitburg-Pr\u00FCm", "Vulkaneifel", "Trier-Saarburg", "Frankenthal (Pfalz), Kreisfreie Stadt",
                    "Kaiserslautern, Kreisfreie Stadt", "Landau in der Pfalz, Kreisfreie Stadt",
                    "Ludwigshafen am Rhein, Kreisfreie Stadt", "Mainz, Kreisfreie Stadt",
                    "Neustadt an der Weinstra\u00DFe, Kreisfreie Stadt", "Pirmasens, Kreisfreie Stadt",
                    "Speyer, Kreisfreie Stadt", "Worms, Kreisfreie Stadt", "Zweibr\u00FCcken, Kreisfreie Stadt",
                    "Alzey-Worms", "Bad D\u00FCrkheim", "Donnersbergkreis", "Germersheim", "Kaiserslautern, Landkreis",
                    "Kusel", "S\u00FCdliche Weinstra\u00DFe", "Rhein-Pfalz-Kreis", "Mainz-Bingen", "S\u00FCdwestpfalz",
                    "Regionalverband Saarbr\u00FCcken", "Merzig-Wadern", "Neunkirchen", "Saarlouis", "Saarpfalz-Kreis",
                    "St. Wendel", "Dresden, Kreisfreie Stadt", "Bautzen", "G\u00F6rlitz", "Mei\u00DFen",
                    "S\u00E4chsische Schweiz-Osterzgebirge", "Chemnitz, Kreisfreie Stadt", "Erzgebirgskreis",
                    "Mittelsachsen", "Vogtlandkreis", "Zwickau", "Leipzig, Kreisfreie Stadt", "Leipzig",
                    "Nordsachsen", "Dessau-Ro\u00DFlau, Kreisfreie Stadt", "Halle (Saale), Kreisfreie Stadt",
                    "Magdeburg, Kreisfreie Stadt", "Altmarkkreis Salzwedel", "Anhalt-Bitterfeld", "Jerichower Land",
                    "B\u00F6rde", "Burgenlandkreis", "Harz", "Mansfeld-S\u00FCdharz", "Saalekreis", "Salzlandkreis", "Stendal",
                    "Wittenberg", "Flensburg, Kreisfreie Stadt", "Kiel, Kreisfreie Stadt", "L\u00FCbeck, Kreisfreie Stadt",
                    "Neum\u00FCnster, Kreisfreie Stadt", "Dithmarschen", "Herzogtum Lauenburg", "Nordfriesland",
                    "Ostholstein", "Pinneberg", "Pl\u00F6n", "Rendsburg-Eckernf\u00F6rde", "Schleswig-Flensburg", "Segeberg",
                    "Steinburg", "Stormarn", "Erfurt, Kreisfreie Stadt", "Gera, Kreisfreie Stadt",
                    "Jena, Kreisfreie Stadt", "Suhl, Kreisfreie Stadt", "Weimar, Kreisfreie Stadt", "Eichsfeld",
                    "Nordhausen", "Unstrut-Hainich-Kreis", "Kyffh\u00E4userkreis", "Schmalkalden-Meiningen", "Gotha",
                    "S\u00F6mmerda", "Hildburghausen", "Ilm-Kreis", "Weimarer Land", "Sonneberg", "Saalfeld-Rudolstadt",
                    "Saale-Holzland-Kreis", "Saale-Orla-Kreis", "Greiz", "Altenburger Land",
                    "Eisenach, Kreisfreie Stadt", "Wartburgkreis", "Paris", "Seine-et-Marne", "Yvelines",
                    "Essonne", "Hauts-de-Seine", "Seine-Saint-Denis", "Val-de-Marne", "Val-d'Oise", "Cher",
                    "Eure-et-Loir", "Indre", "Indre-et-Loire", "Loir-et-Cher", "Loiret", "C\u00F4te-d'Or", "Ni\u00E8vre",
                    "Sa\u00F4ne-et-Loire", "Yonne", "Doubs", "Jura", "Haute-Sa\u00F4ne", "Territoire de Belfort", "Calvados",
                    "Manche", "Orne", "Eure", "Seine-Maritime", "Nord", "Pas-de-Calais", "Aisne", "Oise", "Somme",
                    "Bas-Rhin", "Haut-Rhin", "Ardennes", "Aube", "Marne", "Haute-Marne", "Meurthe-et-Moselle",
                    "Meuse", "Moselle", "Vosges", "Loire-Atlantique", "Maine-et-Loire", "Mayenne", "Sarthe",
                    "Vend\u00E9e", "C\u00F4tes-d'Armor", "Finist\u00E8re", "Ille-et-Vilaine", "Morbihan", "Dordogne", "Gironde",
                    "Landes", "Lot-et-Garonne", "Pyr\u00E9n\u00E9es-Atlantiques", "Corr\u00E8ze", "Creuse", "Haute-Vienne", "Charente",
                    "Charente-Maritime", "Deux-S\u00E8vres", "Vienne", "Aude", "Gard", "H\u00E9rault", "Loz\u00E8re", "Pyr\u00E9n\u00E9es-Orientales",
                    "Ari\u00E8ge", "Aveyron", "Haute-Garonne", "Gers", "Lot", "Hautes-Pyr\u00E9n\u00E9es", "Tarn", "Tarn-et-Garonne", "Allier",
                    "Cantal", "Haute-Loire", "Puy-de-D\u00F4me", "Ain", "Ard\u00E8che", "Dr\u00F4me", "Is\u00E8re", "Loire", "Rh\u00F4ne", "Savoie",
                    "Haute-Savoie", "Alpes-de-Haute-Provence", "Hautes-Alpes", "Alpes-Maritimes", "Bouches-du-Rh\u00F4ne", "Var",
                    "Vaucluse", "Corse-du-Sud", "Haute-Corse", "Torino", "Vercelli", "Biella", "Verbano-Cusio-Ossola", "Novara",
                    "Cuneo", "Asti", "Alessandria", "Valle d'Aosta/Vall\u00E9e d'Aoste", "Imperia", "Savona", "Genova", "La Spezia",
                    "Varese", "Como", "Lecco", "Sondrio", "Bergamo", "Brescia", "Pavia", "Lodi", "Cremona", "Mantova",
                    "Milano", "Monza e della Brianza", "L'Aquila", "Teramo", "Pescara", "Chieti", "Isernia", "Campobasso",
                    "Caserta", "Benevento", "Napoli", "Avellino", "Salerno", "Taranto", "Brindisi", "Lecce", "Foggia",
                    "Bari", "Barletta-Andria-Trani", "Potenza", "Matera", "Cosenza", "Crotone", "Catanzaro", "Vibo Valentia",
                    "Reggio di Calabria", "Trapani", "Palermo", "Messina", "Agrigento", "Caltanissetta", "Enna", "Catania",
                    "Ragusa", "Siracusa", "Sassari", "Nuoro", "Cagliari", "Oristano", "Sud Sardegna", "Bolzano-Bozen",
                    "Trento", "Verona", "Vicenza", "Belluno", "Treviso", "Venezia", "Padova", "Rovigo", "Pordenone",
                    "Udine", "Gorizia", "Trieste", "Piacenza", "Parma", "Reggio nell'Emilia", "Modena", "Bologna",
                    "Ferrara", "Ravenna", "Forl\u00EC-Cesena", "Rimini", "Massa-Carrara", "Lucca", "Pistoia", "Firenze",
                    "Prato", "Livorno", "Pisa", "Arezzo", "Siena", "Grosseto", "Perugia", "Terni", "Pesaro e Urbino",
                    "Ancona", "Macerata", "Ascoli Piceno", "Fermo", "Viterbo", "Rieti", "Roma", "Latina", "Frosinone",
                    "Liechtenstein")
  NUTS_2_NAMES <- c("Burgenland", "Burgenland", "Burgenland", "Nieder\u00F6sterreich", "Nieder\u00F6sterreich",
                    "Nieder\u00F6sterreich", "Nieder\u00F6sterreich", "Nieder\u00F6sterreich", "Nieder\u00F6sterreich",
                    "Nieder\u00F6sterreich", "Wien", "K\u00E4rnten", "K\u00E4rnten", "K\u00E4rnten", "Steiermark", "Steiermark",
                    "Steiermark", "Steiermark", "Steiermark", "Steiermark", "Ober\u00F6sterreich",
                    "Ober\u00F6sterreich", "Ober\u00F6sterreich", "Ober\u00F6sterreich", "Ober\u00F6sterreich", "Salzburg",
                    "Salzburg", "Salzburg", "Tirol", "Tirol", "Tirol", "Tirol", "Tirol", "Vorarlberg",
                    "Vorarlberg", "R\u00E9gion l\u00E9manique", "R\u00E9gion l\u00E9manique", "R\u00E9gion l\u00E9manique", "Espace Mittelland",
                    "Espace Mittelland", "Espace Mittelland", "Espace Mittelland", "Espace Mittelland", "Nordwestschweiz",
                    "Nordwestschweiz", "Nordwestschweiz", "Z\u00FCrich", "Ostschweiz", "Ostschweiz", "Ostschweiz", "Ostschweiz",
                    "Ostschweiz", "Ostschweiz", "Ostschweiz", "Zentralschweiz", "Zentralschweiz", "Zentralschweiz",
                    "Zentralschweiz", "Zentralschweiz", "Zentralschweiz", "Ticino", "Stuttgart", "Stuttgart", "Stuttgart",
                    "Stuttgart", "Stuttgart", "Stuttgart", "Stuttgart", "Stuttgart", "Stuttgart", "Stuttgart", "Stuttgart",
                    "Stuttgart", "Stuttgart", "Karlsruhe", "Karlsruhe", "Karlsruhe", "Karlsruhe", "Karlsruhe", "Karlsruhe",
                    "Karlsruhe", "Karlsruhe", "Karlsruhe", "Karlsruhe", "Karlsruhe", "Karlsruhe", "Freiburg", "Freiburg",
                    "Freiburg", "Freiburg", "Freiburg", "Freiburg", "Freiburg", "Freiburg", "Freiburg", "Freiburg", "T\u00FCbingen",
                    "T\u00FCbingen", "T\u00FCbingen", "T\u00FCbingen", "T\u00FCbingen", "T\u00FCbingen", "T\u00FCbingen", "T\u00FCbingen", "T\u00FCbingen", "Oberbayern",
                    "Oberbayern", "Oberbayern", "Oberbayern", "Oberbayern", "Oberbayern", "Oberbayern", "Oberbayern",
                    "Oberbayern", "Oberbayern", "Oberbayern", "Oberbayern", "Oberbayern", "Oberbayern", "Oberbayern",
                    "Oberbayern", "Oberbayern", "Oberbayern", "Oberbayern", "Oberbayern", "Oberbayern", "Oberbayern",
                    "Oberbayern", "Niederbayern", "Niederbayern", "Niederbayern", "Niederbayern", "Niederbayern",
                    "Niederbayern", "Niederbayern", "Niederbayern", "Niederbayern", "Niederbayern", "Niederbayern",
                    "Niederbayern", "Oberpfalz", "Oberpfalz", "Oberpfalz", "Oberpfalz", "Oberpfalz", "Oberpfalz", "Oberpfalz",
                    "Oberpfalz", "Oberpfalz", "Oberpfalz", "Oberfranken", "Oberfranken", "Oberfranken", "Oberfranken",
                    "Oberfranken", "Oberfranken", "Oberfranken", "Oberfranken", "Oberfranken", "Oberfranken", "Oberfranken",
                    "Oberfranken", "Oberfranken", "Mittelfranken", "Mittelfranken", "Mittelfranken", "Mittelfranken",
                    "Mittelfranken", "Mittelfranken", "Mittelfranken", "Mittelfranken", "Mittelfranken", "Mittelfranken",
                    "Mittelfranken", "Mittelfranken", "Unterfranken", "Unterfranken", "Unterfranken", "Unterfranken",
                    "Unterfranken", "Unterfranken", "Unterfranken", "Unterfranken", "Unterfranken", "Unterfranken",
                    "Unterfranken", "Unterfranken", "Schwaben", "Schwaben", "Schwaben", "Schwaben", "Schwaben", "Schwaben",
                    "Schwaben", "Schwaben", "Schwaben", "Schwaben", "Schwaben", "Schwaben", "Schwaben", "Schwaben", "Berlin",
                    "Brandenburg", "Brandenburg", "Brandenburg", "Brandenburg", "Brandenburg", "Brandenburg", "Brandenburg",
                    "Brandenburg", "Brandenburg", "Brandenburg", "Brandenburg", "Brandenburg", "Brandenburg", "Brandenburg",
                    "Brandenburg", "Brandenburg", "Brandenburg", "Brandenburg", "Bremen", "Bremen", "Hamburg", "Darmstadt",
                    "Darmstadt", "Darmstadt", "Darmstadt", "Darmstadt", "Darmstadt", "Darmstadt", "Darmstadt", "Darmstadt",
                    "Darmstadt", "Darmstadt", "Darmstadt", "Darmstadt", "Darmstadt", "Gie\u00DFen", "Gie\u00DFen", "Gie\u00DFen", "Gie\u00DFen",
                    "Gie\u00DFen", "Kassel", "Kassel", "Kassel", "Kassel", "Kassel", "Kassel", "Kassel", "Mecklenburg-Vorpommern",
                    "Mecklenburg-Vorpommern", "Mecklenburg-Vorpommern", "Mecklenburg-Vorpommern", "Mecklenburg-Vorpommern",
                    "Mecklenburg-Vorpommern", "Mecklenburg-Vorpommern", "Mecklenburg-Vorpommern", "Braunschweig",
                    "Braunschweig", "Braunschweig", "Braunschweig", "Braunschweig", "Braunschweig", "Braunschweig",
                    "Braunschweig", "Braunschweig", "Braunschweig", "Hannover", "Hannover", "Hannover", "Hannover",
                    "Hannover", "Hannover", "Hannover", "L\u00FCneburg", "L\u00FCneburg", "L\u00FCneburg", "L\u00FCneburg", "L\u00FCneburg",
                    "L\u00FCneburg", "L\u00FCneburg", "L\u00FCneburg", "L\u00FCneburg", "L\u00FCneburg", "L\u00FCneburg", "Weser-Ems", "Weser-Ems",
                    "Weser-Ems", "Weser-Ems", "Weser-Ems", "Weser-Ems", "Weser-Ems", "Weser-Ems", "Weser-Ems", "Weser-Ems",
                    "Weser-Ems", "Weser-Ems", "Weser-Ems", "Weser-Ems", "Weser-Ems", "Weser-Ems", "Weser-Ems", "D\u00FCsseldorf",
                    "D\u00FCsseldorf", "D\u00FCsseldorf", "D\u00FCsseldorf", "D\u00FCsseldorf", "D\u00FCsseldorf", "D\u00FCsseldorf", "D\u00FCsseldorf",
                    "D\u00FCsseldorf", "D\u00FCsseldorf", "D\u00FCsseldorf", "D\u00FCsseldorf", "D\u00FCsseldorf", "D\u00FCsseldorf", "D\u00FCsseldorf", "K\u00F6ln",
                    "K\u00F6ln", "K\u00F6ln", "K\u00F6ln", "K\u00F6ln", "K\u00F6ln", "K\u00F6ln", "K\u00F6ln", "K\u00F6ln", "K\u00F6ln", "K\u00F6ln", "M\u00FCnster", "M\u00FCnster",
                    "M\u00FCnster", "M\u00FCnster", "M\u00FCnster", "M\u00FCnster", "M\u00FCnster", "M\u00FCnster", "Detmold", "Detmold", "Detmold",
                    "Detmold", "Detmold", "Detmold", "Detmold", "Arnsberg", "Arnsberg", "Arnsberg", "Arnsberg", "Arnsberg",
                    "Arnsberg", "Arnsberg", "Arnsberg", "Arnsberg", "Arnsberg", "Arnsberg", "Arnsberg", "Koblenz", "Koblenz",
                    "Koblenz", "Koblenz", "Koblenz", "Koblenz", "Koblenz", "Koblenz", "Koblenz", "Koblenz", "Koblenz", "Trier",
                    "Trier", "Trier", "Trier", "Trier", "Rheinhessen-Pfalz", "Rheinhessen-Pfalz", "Rheinhessen-Pfalz",
                    "Rheinhessen-Pfalz", "Rheinhessen-Pfalz", "Rheinhessen-Pfalz", "Rheinhessen-Pfalz", "Rheinhessen-Pfalz",
                    "Rheinhessen-Pfalz", "Rheinhessen-Pfalz", "Rheinhessen-Pfalz", "Rheinhessen-Pfalz", "Rheinhessen-Pfalz",
                    "Rheinhessen-Pfalz", "Rheinhessen-Pfalz", "Rheinhessen-Pfalz", "Rheinhessen-Pfalz", "Rheinhessen-Pfalz",
                    "Rheinhessen-Pfalz", "Rheinhessen-Pfalz", "Saarland", "Saarland", "Saarland", "Saarland", "Saarland",
                    "Saarland", "Dresden", "Dresden", "Dresden", "Dresden", "Dresden", "Chemnitz", "Chemnitz", "Chemnitz",
                    "Chemnitz", "Chemnitz", "Leipzig", "Leipzig", "Leipzig", "Sachsen-Anhalt", "Sachsen-Anhalt",
                    "Sachsen-Anhalt", "Sachsen-Anhalt", "Sachsen-Anhalt", "Sachsen-Anhalt", "Sachsen-Anhalt",
                    "Sachsen-Anhalt", "Sachsen-Anhalt", "Sachsen-Anhalt", "Sachsen-Anhalt", "Sachsen-Anhalt",
                    "Sachsen-Anhalt", "Sachsen-Anhalt", "Schleswig-Holstein", "Schleswig-Holstein", "Schleswig-Holstein",
                    "Schleswig-Holstein", "Schleswig-Holstein", "Schleswig-Holstein", "Schleswig-Holstein",
                    "Schleswig-Holstein", "Schleswig-Holstein", "Schleswig-Holstein", "Schleswig-Holstein",
                    "Schleswig-Holstein", "Schleswig-Holstein", "Schleswig-Holstein", "Schleswig-Holstein", "Th\u00FCringen",
                    "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen",
                    "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen",
                    "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Ile-de-France",
                    "Ile-de-France", "Ile-de-France", "Ile-de-France", "Ile-de-France", "Ile-de-France", "Ile-de-France",
                    "Ile-de-France", "Centre - Val de Loire", "Centre - Val de Loire", "Centre - Val de Loire",
                    "Centre - Val de Loire", "Centre - Val de Loire", "Centre - Val de Loire", "Bourgogne", "Bourgogne",
                    "Bourgogne", "Bourgogne", "Franche-Comt\u00E9", "Franche-Comt\u00E9", "Franche-Comt\u00E9", "Franche-Comt\u00E9",
                    "Basse-Normandie", "Basse-Normandie", "Basse-Normandie", "Haute-Normandie", "Haute-Normandie",
                    "Nord-Pas de Calais", "Nord-Pas de Calais", "Picardie", "Picardie", "Picardie", "Alsace", "Alsace",
                    "Champagne-Ardenne", "Champagne-Ardenne", "Champagne-Ardenne", "Champagne-Ardenne", "Lorraine",
                    "Lorraine", "Lorraine", "Lorraine", "Pays de la Loire", "Pays de la Loire", "Pays de la Loire",
                    "Pays de la Loire", "Pays de la Loire", "Bretagne", "Bretagne", "Bretagne", "Bretagne", "Aquitaine",
                    "Aquitaine", "Aquitaine", "Aquitaine", "Aquitaine", "Limousin", "Limousin", "Limousin", "Poitou-Charentes",
                    "Poitou-Charentes", "Poitou-Charentes", "Poitou-Charentes", "Languedoc-Roussillon", "Languedoc-Roussillon",
                    "Languedoc-Roussillon", "Languedoc-Roussillon", "Languedoc-Roussillon", "Midi-Pyr\u00E9n\u00E9es", "Midi-Pyr\u00E9n\u00E9es",
                    "Midi-Pyr\u00E9n\u00E9es", "Midi-Pyr\u00E9n\u00E9es", "Midi-Pyr\u00E9n\u00E9es", "Midi-Pyr\u00E9n\u00E9es", "Midi-Pyr\u00E9n\u00E9es", "Midi-Pyr\u00E9n\u00E9es",
                    "Auvergne", "Auvergne", "Auvergne", "Auvergne", "Rh\u00F4ne-Alpes", "Rh\u00F4ne-Alpes", "Rh\u00F4ne-Alpes", "Rh\u00F4ne-Alpes",
                    "Rh\u00F4ne-Alpes", "Rh\u00F4ne-Alpes", "Rh\u00F4ne-Alpes", "Rh\u00F4ne-Alpes", "Provence-Alpes-C\u00F4te d'Azur",
                    "Provence-Alpes-C\u00F4te d'Azur", "Provence-Alpes-C\u00F4te d'Azur", "Provence-Alpes-C\u00F4te d'Azur",
                    "Provence-Alpes-C\u00F4te d'Azur", "Provence-Alpes-C\u00F4te d'Azur", "Corse", "Corse", "Piemonte", "Piemonte",
                    "Piemonte", "Piemonte", "Piemonte", "Piemonte", "Piemonte", "Piemonte", "Valle d'Aosta/Vall\u00E9e d'Aoste",
                    "Liguria", "Liguria", "Liguria", "Liguria", "Lombardia", "Lombardia", "Lombardia", "Lombardia",
                    "Lombardia", "Lombardia", "Lombardia", "Lombardia", "Lombardia", "Lombardia", "Lombardia", "Lombardia",
                    "Abruzzo", "Abruzzo", "Abruzzo", "Abruzzo", "Molise", "Molise", "Campania", "Campania", "Campania",
                    "Campania", "Campania", "Puglia", "Puglia", "Puglia", "Puglia", "Puglia", "Puglia", "Basilicata",
                    "Basilicata", "Calabria", "Calabria", "Calabria", "Calabria", "Calabria", "Sicilia", "Sicilia", "Sicilia",
                    "Sicilia", "Sicilia", "Sicilia", "Sicilia", "Sicilia", "Sicilia", "Sardegna", "Sardegna", "Sardegna",
                    "Sardegna", "Sardegna", "Provincia Autonoma di Bolzano/Bozen", "Provincia Autonoma di Trento", "Veneto",
                    "Veneto", "Veneto", "Veneto", "Veneto", "Veneto", "Veneto", "Friuli-Venezia Giulia",
                    "Friuli-Venezia Giulia", "Friuli-Venezia Giulia", "Friuli-Venezia Giulia", "Emilia-Romagna",
                    "Emilia-Romagna", "Emilia-Romagna", "Emilia-Romagna", "Emilia-Romagna", "Emilia-Romagna",
                    "Emilia-Romagna", "Emilia-Romagna", "Emilia-Romagna", "Toscana", "Toscana", "Toscana", "Toscana",
                    "Toscana", "Toscana", "Toscana", "Toscana", "Toscana", "Toscana", "Umbria", "Umbria", "Marche", "Marche",
                    "Marche", "Marche", "Marche", "Lazio", "Lazio", "Lazio", "Lazio", "Lazio", "Liechtenstein")
  NUTS_1_NAMES <- c("Ost\u00F6sterreich", "Ost\u00F6sterreich", "Ost\u00F6sterreich", "Ost\u00F6sterreich", "Ost\u00F6sterreich",
                    "Ost\u00F6sterreich", "Ost\u00F6sterreich", "Ost\u00F6sterreich", "Ost\u00F6sterreich", "Ost\u00F6sterreich",
                    "Ost\u00F6sterreich", "S\u00FCd\u00F6sterreich", "S\u00FCd\u00F6sterreich", "S\u00FCd\u00F6sterreich", "S\u00FCd\u00F6sterreich",
                    "S\u00FCd\u00F6sterreich", "S\u00FCd\u00F6sterreich", "S\u00FCd\u00F6sterreich", "S\u00FCd\u00F6sterreich", "S\u00FCd\u00F6sterreich",
                    "West\u00F6sterreich", "West\u00F6sterreich", "West\u00F6sterreich", "West\u00F6sterreich", "West\u00F6sterreich",
                    "West\u00F6sterreich", "West\u00F6sterreich", "West\u00F6sterreich", "West\u00F6sterreich", "West\u00F6sterreich",
                    "West\u00F6sterreich", "West\u00F6sterreich", "West\u00F6sterreich", "West\u00F6sterreich", "West\u00F6sterreich",
                    "Schweiz", "Schweiz", "Schweiz", "Schweiz", "Schweiz", "Schweiz", "Schweiz", "Schweiz",
                    "Schweiz", "Schweiz", "Schweiz", "Schweiz", "Schweiz", "Schweiz", "Schweiz", "Schweiz",
                    "Schweiz", "Schweiz", "Schweiz", "Schweiz", "Schweiz", "Schweiz", "Schweiz", "Schweiz",
                    "Schweiz", "Schweiz", "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg",
                    "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg",
                    "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg",
                    "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg",
                    "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg",
                    "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg",
                    "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg",
                    "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg",
                    "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg",
                    "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg",
                    "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg", "Baden-W\u00FCrttemberg",
                    "Baden-W\u00FCrttemberg", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern",
                    "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern",
                    "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern",
                    "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern",
                    "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern",
                    "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern",
                    "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern",
                    "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern",
                    "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern",
                    "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern",
                    "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Bayern", "Berlin",
                    "Brandenburg", "Brandenburg", "Brandenburg", "Brandenburg", "Brandenburg", "Brandenburg",
                    "Brandenburg", "Brandenburg", "Brandenburg", "Brandenburg", "Brandenburg", "Brandenburg",
                    "Brandenburg", "Brandenburg", "Brandenburg", "Brandenburg", "Brandenburg", "Brandenburg",
                    "Bremen", "Bremen", "Hamburg", "Hessen", "Hessen", "Hessen", "Hessen", "Hessen", "Hessen",
                    "Hessen", "Hessen", "Hessen", "Hessen", "Hessen", "Hessen", "Hessen", "Hessen", "Hessen",
                    "Hessen", "Hessen", "Hessen", "Hessen", "Hessen", "Hessen", "Hessen", "Hessen", "Hessen",
                    "Hessen", "Hessen", "Mecklenburg-Vorpommern", "Mecklenburg-Vorpommern", "Mecklenburg-Vorpommern",
                    "Mecklenburg-Vorpommern", "Mecklenburg-Vorpommern", "Mecklenburg-Vorpommern", "Mecklenburg-Vorpommern",
                    "Mecklenburg-Vorpommern", "Niedersachsen", "Niedersachsen", "Niedersachsen", "Niedersachsen",
                    "Niedersachsen", "Niedersachsen", "Niedersachsen", "Niedersachsen", "Niedersachsen",
                    "Niedersachsen", "Niedersachsen", "Niedersachsen", "Niedersachsen", "Niedersachsen",
                    "Niedersachsen", "Niedersachsen", "Niedersachsen", "Niedersachsen", "Niedersachsen",
                    "Niedersachsen", "Niedersachsen", "Niedersachsen", "Niedersachsen", "Niedersachsen",
                    "Niedersachsen", "Niedersachsen", "Niedersachsen", "Niedersachsen", "Niedersachsen",
                    "Niedersachsen", "Niedersachsen", "Niedersachsen", "Niedersachsen", "Niedersachsen",
                    "Niedersachsen", "Niedersachsen", "Niedersachsen", "Niedersachsen", "Niedersachsen",
                    "Niedersachsen", "Niedersachsen", "Niedersachsen", "Niedersachsen", "Niedersachsen",
                    "Niedersachsen", "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen",
                    "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen",
                    "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen",
                    "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen",
                    "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen",
                    "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen",
                    "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen",
                    "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen",
                    "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen",
                    "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen",
                    "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen",
                    "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen",
                    "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Nordrhein-Westfalen",
                    "Nordrhein-Westfalen", "Nordrhein-Westfalen", "Rheinland-Pfalz", "Rheinland-Pfalz",
                    "Rheinland-Pfalz", "Rheinland-Pfalz", "Rheinland-Pfalz", "Rheinland-Pfalz", "Rheinland-Pfalz",
                    "Rheinland-Pfalz", "Rheinland-Pfalz", "Rheinland-Pfalz", "Rheinland-Pfalz", "Rheinland-Pfalz",
                    "Rheinland-Pfalz", "Rheinland-Pfalz", "Rheinland-Pfalz", "Rheinland-Pfalz", "Rheinland-Pfalz",
                    "Rheinland-Pfalz", "Rheinland-Pfalz", "Rheinland-Pfalz", "Rheinland-Pfalz", "Rheinland-Pfalz",
                    "Rheinland-Pfalz", "Rheinland-Pfalz", "Rheinland-Pfalz", "Rheinland-Pfalz", "Rheinland-Pfalz",
                    "Rheinland-Pfalz", "Rheinland-Pfalz", "Rheinland-Pfalz", "Rheinland-Pfalz", "Rheinland-Pfalz",
                    "Rheinland-Pfalz", "Rheinland-Pfalz", "Rheinland-Pfalz", "Rheinland-Pfalz", "Saarland",
                    "Saarland", "Saarland", "Saarland", "Saarland", "Saarland", "Sachsen", "Sachsen", "Sachsen",
                    "Sachsen", "Sachsen", "Sachsen", "Sachsen", "Sachsen", "Sachsen", "Sachsen", "Sachsen",
                    "Sachsen", "Sachsen", "Sachsen-Anhalt", "Sachsen-Anhalt", "Sachsen-Anhalt", "Sachsen-Anhalt",
                    "Sachsen-Anhalt", "Sachsen-Anhalt", "Sachsen-Anhalt", "Sachsen-Anhalt", "Sachsen-Anhalt",
                    "Sachsen-Anhalt", "Sachsen-Anhalt", "Sachsen-Anhalt", "Sachsen-Anhalt", "Sachsen-Anhalt",
                    "Schleswig-Holstein", "Schleswig-Holstein", "Schleswig-Holstein", "Schleswig-Holstein",
                    "Schleswig-Holstein", "Schleswig-Holstein", "Schleswig-Holstein", "Schleswig-Holstein",
                    "Schleswig-Holstein", "Schleswig-Holstein", "Schleswig-Holstein", "Schleswig-Holstein",
                    "Schleswig-Holstein", "Schleswig-Holstein", "Schleswig-Holstein", "Th\u00FCringen",
                    "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen",
                    "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen",
                    "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen", "Th\u00FCringen",
                    "Th\u00FCringen", "Ile-de-France", "Ile-de-France", "Ile-de-France", "Ile-de-France", "Ile-de-France",
                    "Ile-de-France", "Ile-de-France", "Ile-de-France", "Centre - Val de Loire",
                    "Centre - Val de Loire", "Centre - Val de Loire", "Centre - Val de Loire",
                    "Centre - Val de Loire", "Centre - Val de Loire", "Bourgogne - Franche-Comt\u00E9",
                    "Bourgogne - Franche-Comt\u00E9", "Bourgogne - Franche-Comt\u00E9", "Bourgogne - Franche-Comt\u00E9",
                    "Bourgogne - Franche-Comt\u00E9", "Bourgogne - Franche-Comt\u00E9", "Bourgogne - Franche-Comt\u00E9",
                    "Bourgogne - Franche-Comt\u00E9", "Normandie", "Normandie", "Normandie", "Normandie", "Normandie",
                    "Hauts-de-France", "Hauts-de-France", "Hauts-de-France", "Hauts-de-France", "Hauts-de-France",
                    "Grand Est", "Grand Est", "Grand Est", "Grand Est", "Grand Est", "Grand Est", "Grand Est",
                    "Grand Est", "Grand Est", "Grand Est", "Pays de la Loire", "Pays de la Loire",
                    "Pays de la Loire", "Pays de la Loire", "Pays de la Loire", "Bretagne", "Bretagne",
                    "Bretagne", "Bretagne", "Nouvelle-Aquitaine", "Nouvelle-Aquitaine", "Nouvelle-Aquitaine",
                    "Nouvelle-Aquitaine", "Nouvelle-Aquitaine", "Nouvelle-Aquitaine", "Nouvelle-Aquitaine",
                    "Nouvelle-Aquitaine", "Nouvelle-Aquitaine", "Nouvelle-Aquitaine", "Nouvelle-Aquitaine",
                    "Nouvelle-Aquitaine", "Occitanie", "Occitanie", "Occitanie", "Occitanie", "Occitanie",
                    "Occitanie", "Occitanie", "Occitanie", "Occitanie", "Occitanie", "Occitanie", "Occitanie",
                    "Occitanie", "Auvergne - Rh\u00F4ne-Alpes", "Auvergne - Rh\u00F4ne-Alpes", "Auvergne - Rh\u00F4ne-Alpes",
                    "Auvergne - Rh\u00F4ne-Alpes", "Auvergne - Rh\u00F4ne-Alpes", "Auvergne - Rh\u00F4ne-Alpes",
                    "Auvergne - Rh\u00F4ne-Alpes", "Auvergne - Rh\u00F4ne-Alpes", "Auvergne - Rh\u00F4ne-Alpes",
                    "Auvergne - Rh\u00F4ne-Alpes", "Auvergne - Rh\u00F4ne-Alpes", "Auvergne - Rh\u00F4ne-Alpes",
                    "Provence-Alpes-C\u00F4te d'Azur", "Provence-Alpes-C\u00F4te d'Azur", "Provence-Alpes-C\u00F4te d'Azur",
                    "Provence-Alpes-C\u00F4te d'Azur", "Provence-Alpes-C\u00F4te d'Azur", "Provence-Alpes-C\u00F4te d'Azur",
                    "Corse", "Corse", "Nord-Ovest", "Nord-Ovest", "Nord-Ovest", "Nord-Ovest", "Nord-Ovest",
                    "Nord-Ovest", "Nord-Ovest", "Nord-Ovest", "Nord-Ovest", "Nord-Ovest", "Nord-Ovest",
                    "Nord-Ovest", "Nord-Ovest", "Nord-Ovest", "Nord-Ovest", "Nord-Ovest", "Nord-Ovest",
                    "Nord-Ovest", "Nord-Ovest", "Nord-Ovest", "Nord-Ovest", "Nord-Ovest", "Nord-Ovest",
                    "Nord-Ovest", "Nord-Ovest", "Sud", "Sud", "Sud", "Sud", "Sud", "Sud", "Sud", "Sud",
                    "Sud", "Sud", "Sud", "Sud", "Sud", "Sud", "Sud", "Sud", "Sud", "Sud", "Sud", "Sud",
                    "Sud", "Sud", "Sud", "Sud", "Isole", "Isole", "Isole", "Isole", "Isole", "Isole",
                    "Isole", "Isole", "Isole", "Isole", "Isole", "Isole", "Isole", "Isole", "Nord-Est",
                    "Nord-Est", "Nord-Est", "Nord-Est", "Nord-Est", "Nord-Est", "Nord-Est", "Nord-Est",
                    "Nord-Est", "Nord-Est", "Nord-Est", "Nord-Est", "Nord-Est", "Nord-Est", "Nord-Est",
                    "Nord-Est", "Nord-Est", "Nord-Est", "Nord-Est", "Nord-Est", "Nord-Est", "Nord-Est",
                    "Centro (IT)", "Centro (IT)", "Centro (IT)", "Centro (IT)", "Centro (IT)", "Centro (IT)",
                    "Centro (IT)", "Centro (IT)", "Centro (IT)", "Centro (IT)", "Centro (IT)", "Centro (IT)",
                    "Centro (IT)", "Centro (IT)", "Centro (IT)", "Centro (IT)", "Centro (IT)", "Centro (IT)",
                    "Centro (IT)", "Centro (IT)", "Centro (IT)", "Centro (IT)", "Liechtenstein")
  nuts <- data.frame(NUTS_3 = NUTS_3,
                     NUTS_3_NAME = NUTS_3_NAMES,
                     NUTS_2_NAME = NUTS_2_NAMES,
                     NUTS_1_NAME = NUTS_1_NAMES)
  nuts <- nuts %>%
    mutate(NUTS_2 = substr(NUTS_3, 1, 4),
           NUTS_1 = substr(NUTS_3, 1, 3),
           CNTR_CODE = substr(NUTS_3, 1, 2)) %>%
    select(CNTR_CODE, NUTS_3, NUTS_3_NAME, NUTS_2, NUTS_2_NAME, NUTS_1, NUTS_1_NAME)

  # save data as .RDS to cache_dir
  saveRDS(object = nuts, file = paste0(cache_dir, "/nuts_table.RDS"))

  return(nuts)
}
